#version: '3'

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - ASPNET_URLS=http://+:5000
      - ASPNET_ENVIRONMENT=Production
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab5
    ports:
      - "5432:5432"
  adminer:
    image: adminer:standalone
    depends_on:
      - backend
    ports:
      - "8080:8080"


