apiVersion: v1
kind: Pod
metadata:
  name: hellonode
  labels:
    app: hellonode
    version: v0.1
spec:
  containers:
  - name: hellonode
    image: hellonode:v0.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3000

